trigger:
- master
- feature/*

jobs:
  - job: UnitTests
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      buildConfiguration: 'Release'

    steps:
    - script: dotnet test --configuration $(buildConfiguration)
      displayName: 'dotnet test $(buildConfiguration)'
