trigger:
- master

jobs:
- job: UnitTests
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    buildConfiguration: 'Release'

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      arguments: '--configuration $(buildConfiguration)'
